encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.entry,name="entry"),
    path("create",views.create,name="create"),
    path("search<str:query>", views.search, name="search"),
    path("random",views.random,name="random"),
    path("edit/<str:entry>",views.edit,name="edit")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django import forms
from random import choice

from . import util
common={'class': 'form-control'}   
class CreateForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Page Title'}|common))
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Page Content (in markdown)'}|common))

class EditForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea(attrs=common))
    
    
def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if title.lower() in [t.lower() for t in util.list_entries()]:
                return render(request, "encyclopedia/create.html",{"form": form,"invalid":True})
            else:
                util.save_entry(title=title,content=form.cleaned_data["content"])
                return HttpResponseRedirect(f"wiki/{title}")
        else:
            return render(request, "encyclopedia/create.html",{"form": form})
    else:
        return render(request, "encyclopedia/create.html",{"form": CreateForm()})

def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries(),})

def entry(request, title):
    page = util.entry2html(title)
    if(page == None):
        return render(request, "encyclopedia/notfound.html", {
        "title": title
    })
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": page,
        })
    
def search(request,query):
    query = request.GET.get('q')
    if query in util.list_entries():
        return HttpResponseRedirect(f"wiki/{query}")
    return render(request,"encyclopedia/search.html",{
            "query": query,
            "entries": [entry for entry in util.list_entries() if query.lower() in entry.lower()],})

def random(request):
    return HttpResponseRedirect(f"wiki/{choice(util.list_entries())}")

def edit(request,entry):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            util.save_entry(title=entry,content=form.cleaned_data["content"].replace("\r\n","\n"))
            return HttpResponseRedirect(f"../wiki/{entry}")
    else:
        return render(request,"encyclopedia/edit.html",{"title": entry,"form": EditForm(initial={'content': util.get_entry(entry)})})
    

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
Create New Page
{% endblock %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="form-group mx-1 my-1">
    {{form.title.as_field_group}}
    {% if invalid %}
    <div class="alert alert-danger">An entry with this title already exists!</div>
    {% endif %}
    </div>
    <div class="form-group mx-1 my-1">
    {{form.content.as_field_group}}
    </div>
    <div class="d-grid gap-2">
    <input type="submit" class="btn btn-primary btn-block" value="Create">
    </div>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
Edit: {{title}}
{% endblock%}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="form-group mx-1 my-1">
        {{form.content.as_field_group}}
    </div>
    <div class="d-grid gap-2">
        <input type="submit" class="btn btn-primary" value="Save">
    </div>
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
{{title}}
{% endblock %}
{% block body %}
{% for key in content%}
{{key | safe}}
{% endfor %}
<a href="{% url 'encyclopedia:edit' entry=title%}">Edit this page ✏</a>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry%}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <nav class="navbar navbar-expand-lg" style="background-color: #f0f0f0;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Wiki</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'encyclopedia:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'encyclopedia:create' %}">Create New Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'encyclopedia:random'%}">Random Page</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" action="{% url 'encyclopedia:search' query=' '%}">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search Encyclopedia" aria-label="Search" required="required">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="main">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/notfound.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Not Found</title>
        <link href="{% static 'encyclopedia/nfstyle.css' %}" rel="stylesheet">
    </head>
    <body>
        <img src="{% static 'encyclopedia/notfound.jpeg' %}" alt="a detective snake">
        <h1>Not Found</h1>
        <p>An entry for "{{ title }}" could not be found.</p>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
Search Results
{% endblock%}
{% block body%}
<h1>Search Results for: {{query}}</h1>
<ul>
{% for entry in entries %}
    <li><a href="{% url 'encyclopedia:entry' title=entry%}">{{entry}}</a></li>
{% endfor %}
</ul>
{% endblock%}